server:
  port: 8080
  servlet:
    session:
      timeout: 60m  # Session timeout
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: optional:file:.env[.properties]
  application:
    name: service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cookscorner}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: utkaleg@gmail.com
    password: lxkq gudf tlss fcay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

elasticsearch:
  host: ${ELASTICSEARCH_HOST_CORE:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:elastic}
  index-names:
    recipe_index: recipe_index

management:
  endpoint:
    web:
      exposure:
        include: "*"



app:
  baseUrl: http://cookscorner

