server:
  port: 8080
  servlet:
    session:
      timeout: 60m  # Session timeout


spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: optional:file:.env[.properties]
  application:
    name: service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cookscorner}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: utkaleg@gmail.com
    password: lxkq gudf tlss fcay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  elasticsearch:
    username: elastic
    password: elastic
    uris: "localhost:9200"

management:
  endpoint:
    web:
      exposure:
        include: "*"

app:
  baseUrl: http://cookscorner

